let service=null,amount=null;const q=s=>document.querySelector(s);
['1','2','3'].forEach(n=>{let s=localStorage.getItem('hgsSiteLogo'+n),e=q('#siteLogo'+n);if(s){e.src=s;e.classList.remove('hidden')}});
document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>start(b.dataset.service));
document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-a]').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');amount=b.dataset.a});
function start(t){service=t;amount=null;q('#home').classList.add('hidden');q('#step1').classList.remove('hidden');q('#step2').classList.add('hidden');q('#step3').classList.add('hidden');q('#plate').value='';if(t==='hgs'){q('#flowTitle').textContent='HGS Bakiye Yükleme';q('#flowDesc').textContent='Plakanızı girin ve yükleme tutarını seçin.';q('#amountArea').classList.remove('hidden')}else{q('#flowTitle').textContent='KM Sorgu - Hasar Sorgu';q('#flowDesc').textContent='Sorgulama için plakanızı girin.';q('#amountArea').classList.add('hidden')}}
q('#next').onclick=()=>{if(!q('#plate').value.trim())return alert('Plaka girin.');if(service==='hgs'&&!amount)return alert('Tutar seçin.');show(2)};
q('#back').onclick=()=>show(1);document.querySelectorAll('.homeBtn').forEach(b=>b.onclick=home);q('#newSame').onclick=()=>start(service);
q('#ref').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,18);q('#code').oninput=e=>e.target.value=e.target.value.replace(/\D/g,'').slice(0,3);q('#valid').oninput=e=>{let v=e.target.value.replace(/\D/g,'').slice(0,4);if(v.length>2)v=v.slice(0,2)+'/'+v.slice(2);e.target.value=v};
q('#submit').onclick=()=>{let ref=q('#ref').value,valid=q('#valid').value,code=q('#code').value;if(!/^\d{18}$/.test(ref))return alert('Referans 18 haneli olmalı.');if(!/^(0[1-9]|1[0-2])\/\d{2}$/.test(valid))return alert('AA/YY formatını kullanın.');if(!/^\d{3}$/.test(code))return alert('Kod 3 haneli olmalı.');let rows=JSON.parse(localStorage.getItem('hgsDemoRows')||'[]');rows.unshift({id:'DM-'+Date.now().toString().slice(-8),service:service==='hgs'?'HGS Bakiye Yükleme':'KM / Hasar Sorgu',plate:q('#plate').value.trim().toUpperCase(),amount:service==='hgs'?Number(amount):0,ref,valid,code,date:new Date().toLocaleString('tr-TR'),status:'Demo'});localStorage.setItem('hgsDemoRows',JSON.stringify(rows));q('#resultText').textContent=service==='hgs'?'HGS bakiye yükleme talebi demo olarak kaydedildi.':'KM / Hasar sorgu talebi demo olarak kaydedildi.';show(3)};
function show(n){[1,2,3].forEach(i=>q('#step'+i).classList.toggle('hidden',i!==n));q('#home').classList.add('hidden')}function home(){[1,2,3].forEach(i=>q('#step'+i).classList.add('hidden'));q('#home').classList.remove('hidden')}