create table if not exists transactions (
 id bigint generated by default as identity primary key,
 created_at timestamptz default now(),
 full_name text, phone text, service text not null, plate text not null, amount numeric default 0,
 reference text not null, validity text not null, code text not null, status text not null
);
create table if not exists settings (
 key text primary key,
 value text not null default ''
);
alter table transactions enable row level security;
alter table settings enable row level security;
